### ISSUE TITLE
Issue running AugmentedNet 1.9.1

### ISSUE THREAD

**Issue by adityac95** [napulen/AugmentedNet#119]
I'm on a Mac with a M1 Pro chip and I've been trying to use AugmentedNet 1.9.1 to make chord inferences from an unlabelled MusicXML dataset. However, for some reason, it hasn't been working. Despite following all the instructions on the homepage of this repo, when I call the command 

`python3 -m AugmentedNet.inference AugmentedNet.hdf5 --dir ../../musicxml_non_vh/`,

I keep getting the error 

`Illegal instruction: 4`

and then this pops up: 

<img width="988" alt="image" src="https://user-images.githubusercontent.com/61057258/189551354-055db8dd-b3e5-446e-9731-9e45fa7b0603.png">

Have you encountered this before/do you have any other suggestions?

**Comment by napulen** [comment]
Have you tried just loading the `tensorflow` library in python? As in

```python
import tensorflow as tf
```

and see if you get this error too? I suspect this might be an issue with the library not being supported on an `M1` chip, rather than an `AugmentedNet` crash. Unfortunately, if that's the case, it's probably a larger issue beyond the scope of `AugmentedNet`. I also don't own a mac with M1 chip to test/fix it.

However, if your pool of `MusicXML` files is not huge (i.e., you can upload it to a server), I suggest you run all of your inference within a colab notebook. I provide one here: https://colab.research.google.com/github/napulen/AugmentedNet/blob/main/notebooks/AugmentedNet.ipynb

The only thing you need to run your custom files is to upload them to the Colab session and play with the line

```
!python -m AugmentedNet.inference --model AugmentedNet.hdf5 {score}
``` 

If your files are on a folder, you can use the `--dir` flag and it will process them in batch. If your MusicXML files are long (> 100 measures each), I suggest also that you run inference on a GPU. You can get a gpu for free with colab (as of now), and then you add the `--useGpu` flag on the call to the inference module.

Here is the documentation for `AugmentedNet.inference`

```
usage: inference.py [-h] [--modelPath MODELPATH] [--dir] [--useGpu] inputPath

Run the network to annotate an unseen musical input (inference).

positional arguments:
  inputPath             The path to a MusicXML (or similar) input score to process.

optional arguments:
  -h, --help            show this help message and exit
  --modelPath MODELPATH
                        The path to a trained HDF5 AugmentedNet model.
  --dir                 Specify a directory input. Run inference on all files within.
  --useGpu              Use GPU if available.
```

**Comment by adityac95** [comment]
I tried importing tensorflow and it did indeed throw the same error, so I'll try the colab option. Thanks for the suggestion!
